<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7b3ea95e-d678-4e18-aeda-ad3425bf8b73</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JevTicketRouter.Infrastructure\JevTicketRouter.Infrastructure.csproj" />
    <ProjectReference Include="..\JevTicketRouter.Application\JevTicketRouter.Application.csproj" />
  </ItemGroup>

</Project>
